System hostname = openbsd
Password for root = bsd
Do you expect to run the X Window System = no
Change the default console to com0 = yes
Setup a user = bsd
Full name for user = BSD
Password for user = bsd
Public ssh key for user = ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKwwjTrMqIhN8OnhvxJ9fAN3PiHdXIzrFHKBtxw7/nTA daniel@neftis
What network interface do you wish to configure = vio0
IPv4 address for vio0 = autoconf
IPv6 address for vio0 = none
Which disk is the root disk = sd0
Use (W)hole disk MBR or (G)PT = G
Set up a layout = auto
Set up a layout = custom
URL to use for custom disklabel layout = custom_disklabel.conf
URL to get autoinstall responses from = none
Location of sets = cd0
Set name(s) = +* -game*
Perform non-open source component installation = yes
What timezone are you in = UTC
Location of sets = http
HTTP Server = cdn.openbsd.org
